from ctypes import Structure, c_int
from enum import Enum

class orientation(Enum):
    ORIENTATION_NULL = -1
    ORIENTATION_NONE = 0
    ORIENTATION_FLIP_Y = 1
    ORIENTATION_FLIP_X = 2
    ORIENTATION_SWAP_XY = 4
    ORIENTATION_FLIP_HORIZONTALLY = ORIENTATION_FLIP_X
    ORIENTATION_FLIP_VERTICALLY = ORIENTATION_FLIP_Y
    ORIENTATION_ROTATE_180_DEG = ORIENTATION_FLIP_Y | ORIENTATION_FLIP_X
    ORIENTATION_TRANSPOSE = ORIENTATION_SWAP_XY
    ORIENTATION_ROTATE_CCW_90_DEG = ORIENTATION_FLIP_X | ORIENTATION_SWAP_XY
    ORIENTATION_ROTATE_CW_90_DEG = ORIENTATION_FLIP_Y | ORIENTATION_SWAP_XY
    ORIENTATION_TRANSVERSE = ORIENTATION_FLIP_X | ORIENTATION_FLIP_Y | ORIENTATION_SWAP_XY

class flip_params(Structure):
    _operation = 'flip'
    _version = 2
    _fields_ = [('orientation', c_int)]
